name: spectra_example
description: Example usage of the spectra package

environment:
  sdk: ^3.0.0

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  spectra_schema:
    path: ../

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
