name: spectra_schema
description: >-
  A powerful Dart code generator that transforms your data classes into
  JSON Schema, OpenAPI, and Protobuf specifications. Perfect for AI integrations
  and API documentation.
version: 2.0.0
homepage: https://github.com/shtse8/spectra
repository: https://github.com/shtse8/spectra

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  meta: ^1.15.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  build_test: ^2.2.2
