name: soti_schema_plus
description: A tool for generating schemas from Dart data classes.
version: 1.3.0
homepage: https://github.com/csells/soti_schema_plus
repository: https://github.com/csells/soti_schema_plus

environment:
  sdk: ^3.7.2

dependencies:
  analyzer: ^8.2.0
  build: ^4.0.1
  source_gen: ^4.0.1
  meta: ^1.10.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.11.0
  lints: ^6.0.0
  test: ^1.25.8
